const datas = {
    Recipes: {
        classic: {
            milk: 166.67,
            flour: 83.34,
            eggs: 1,
            cornstarch: 0,
            oil: 0.34,
            salt: 0.34,
            crepe: 3.9,
            water: 0,
            yeast: 0,
        },
        vegan: {
            milk: 116.07,
            flour: 50,
            eggs: 0,
            cornstarch: 8.93,
            oil: 0.18,
            salt: 0.18,
            crepe: 1.7,
            water: 0,
            yeast: 0,
        },
        bretonne: {
            milk: 0,
            flour: 165,
            eggs: 1,
            cornstarch: 0,
            oil: 0,
            salt: 5,
            crepe: 6,
            water: 375,
            yeast: 0,
        },
        pancake: {
            milk: 75,
            flour: 75,
            eggs: 1,
            cornstarch: 15,
            oil: 0,
            salt: 0,
            crepe: 0,
            yeast: 3,
        },
        vide: {
            milk: 0,
            flour: 0,
            eggs: 0,
            cornstarch: 0,
            oil: 0,
            salt: 0,
            crepe: 0,
            water: 0,
            yeast: 0,
        },
    }
}

export default datas;